# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Langue par défaut de l'application
    default_locale: 'fr'

    # Activation du composant de traduction
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'fr'

    # La session démarre seulement si elle est lue/écrite
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
