# config/packages/mailer.yaml
framework:
    mailer:
        # Utilise la valeur de MAILER_DSN (ex: smtp://127.0.0.1:1025 pour MailHog en DEV).
        # Le "resolve:" permet de résoudre proprement les références d'env imbriquées si besoin.
        dsn: '%env(resolve:MAILER_DSN)%'
