# config/packages/messenger.yaml
framework:
    messenger:
        # File d'échec commune
        failure_transport: failed

        transports:
            # Transport async (Doctrine, Redis, etc.) défini via l'env
            # Exemple env : MESSENGER_TRANSPORT_DSN=doctrine://default
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            # File d'échec
            failed: 'doctrine://default?queue_name=failed'

            # ⚠ Ne pas définir de transport "sync" ici (on le réserve aux overrides dev)
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # En prod : on garde l'envoi des mails en asynchrone
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            # App\Message\YourMessage: async
