security:
    # Gestion du hash des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Optionnel mais utile : un admin hérite des droits user
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            user_checker: App\Security\UserChecker

            # Anti brute-force (ajuste si besoin)
            login_throttling:
                max_attempts: 5        # 5 tentatives avant ralentissement
                interval: '1 minute'   # fenêtre de calcul

            logout:
                path: app_logout
                target: home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
                # always_remember_me: true

    access_control:
        # accès public
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/verify/email, roles: PUBLIC_ACCESS }
        - { path: ^/verify/resend, roles: PUBLIC_ACCESS }   # renvoi d’email public

        # accès réservé aux utilisateurs connectés
        - { path: ^/profile, roles: ROLE_USER }

        # accès réservé aux administrateurs
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
