security:
    # Gestion du hash des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            user_checker: App\Security\UserChecker

            login_throttling:
                max_attempts: 5
                interval: '1 minute'

            logout:
                path: app_logout
                target: home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # accès public
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/verify/email, roles: PUBLIC_ACCESS }
        - { path: ^/verify/resend, roles: PUBLIC_ACCESS }

        # accès réservé aux utilisateurs connectés
        - { path: ^/account, roles: ROLE_USER }   # <-- Mon compte (infos, MDP, commandes)
        - { path: ^/profile, roles: ROLE_USER }   # (si tu as encore des pages /profile)

        # accès réservé aux administrateurs
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
