twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    date:
        timezone: 'Europe/Paris'

    globals:
        bank_holder: '%bank.holder%'
        bank_bankname: '%bank.bankname%'
        bank_iban: '%bank.iban%'
        bank_bic: '%bank.bic%'

when@test:
    twig:
        strict_variables: true
