vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /uploads/articles
            upload_destination: '%kernel.project_dir%/public/uploads/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

        article_gallery:
            uri_prefix: /uploads/articles/gallery
            upload_destination: '%kernel.project_dir%/public/uploads/articles/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
